# This is a generated file. Not intended for manual editing.
services:
  testtask:
    build:
      context: "C:\\Users\\Vladimir\\Desktop\\CRMTestTask\\CRMProjectTestTask"
      dockerfile: "TestTask/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/TestTask.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net7.0/TestTask.staticwebassets.runtime.CT.json"
    image: "testtask:dev"
    ports: []
    volumes:
    - "C:\\Users\\Vladimir\\Desktop\\CRMTestTask\\CRMProjectTestTask\\TestTask:/app:rw"
    working_dir: "/app"
